# Generated by Django 2.2.5 on 2020-11-24 11:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_of_birth', models.DateTimeField()),
                ('profile_image', models.ImageField(max_length=200, upload_to='')),
                ('Phone_number', models.CharField(max_length=200)),
                ('Email', models.EmailField(max_length=200)),
                ('adress', models.CharField(max_length=200)),
                ('facebook_url', models.CharField(max_length=200)),
                ('instagram_url', models.CharField(max_length=200)),
                ('twitter_url', models.CharField(max_length=200)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
