# Generated by Django 2.2.5 on 2020-11-24 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20201124_1131'),
    ]

    operations = [
        migrations.AddField(
            model_name='UserProfile',
            name='firstname',
            field=models.CharField(default='eg. Jogn', max_length=255),
        ),
        migrations.AddField(
            model_name='UserProfile',
            name='lastname',
            field=models.CharField(default='eg. Doe', max_length=255),
        ),
    ]
