# Generated by Django 2.2.5 on 2020-11-26 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_auto_20201126_0927'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='info',
            field=models.TextField(max_length=500, null=True),
        ),
    ]
