# Generated by Django 2.2.5 on 2020-11-26 14:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipe', '0006_auto_20201126_1405'),
    ]

    operations = [
        migrations.RenameField(
            model_name='item',
            old_name='item_image',
            new_name='image',
        ),
    ]
