# Generated by Django 2.2.5 on 2020-11-27 18:54

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('recipe', '0007_auto_20201126_1418'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='ingredients',
            field=models.CharField(default=django.utils.timezone.now, max_length=250),
            preserve_default=False,
        ),
    ]
