# Generated by Django 2.2.5 on 2020-12-01 22:04

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('recipe', '0009_item_likes'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='Dislikes',
            field=models.ManyToManyField(related_name='dislikes', to=settings.AUTH_USER_MODEL),
        ),
    ]
